import { StyleSheet } from "react-native";
// Admin dashboard, sidebar, summary cards and building rows.
export const styles = StyleSheet.create({
  // Page and Responsive Sidebar
  screen: { flex: 1, backgroundColor: "#F4EFE4" },
  layout: { flex: 1, flexDirection: "row" },
  layoutCompact: { flexDirection: "column" },
  loading: { flex: 1, justifyContent: "center", alignItems: "center" },
  sidebar: { width: 220, backgroundColor: "#991F2B", overflow: "hidden" },
  sidebarCompact: { width: "100%", height: 100 },
  sidebarPhoto: {
    position: "absolute",
    bottom: 0,
    width: "100%",
    height: "70%",
    opacity: 0.2,
  },
  sidebarWaves: { position: "absolute", bottom: 0, width: "100%", height: 100 },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    zIndex: 1,
  },
  logo: { width: 82, height: 82 },
  brand: { fontFamily: "DashboardBrand", fontSize: 25, color: "white" },
  gold: { color: "#FEBF1F" },
  main: { flex: 1 },
  mainContent: { padding: 20, gap: 16 },
  // Heading and Account
  header: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  headingGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
    minWidth: 260,
  },
  headingCopy: { flex: 1 },
  title: { fontFamily: "DashboardMedium", fontSize: 27, color: "#971F2A" },
  small: { fontFamily: "DashboardRegular", fontSize: 13, color: "#3C4147" },
  account: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: "white",
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D6D2CA",
  },
  avatar: { width: 44, height: 44 },
  notice: { fontFamily: "DashboardRegular", color: "#971F2A", fontSize: 13 },
  // Summary Cards
  summaries: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  summary: {
    flex: 1,
    minWidth: 190,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    padding: 14,
    backgroundColor: "white",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#D6D2CA",
  },
  summaryCopy: { flex: 1 },
  selected: { borderColor: "#AF2532", backgroundColor: "#FFF6E6" },
  iconCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "#FFD044",
    alignItems: "center",
    justifyContent: "center",
  },
  count: { fontFamily: "DashboardMedium", fontSize: 25, color: "#AF2532" },
  chevron: { fontSize: 28, color: "#6C757D" },
  // Search Controls — sized like the design, separate from editor inputs
  tablePanel: {
    backgroundColor: "white",
    borderRadius: 24,
    padding: 24,
    borderWidth: 1,
    borderColor: "#D6D2CA",
  },
  toolbar: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 10,
  },
  searchBox: {
    width: "50%",
    minWidth: 220,
    height: 38,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#D6D6D6",
    borderRadius: 7,
  },
  tableSearch: {
    flex: 1,
    minWidth: 0,
    fontFamily: "DashboardRegular",
    fontSize: 13,
    color: "#3C4147",
    height: 36,
  },
  search: {
    flexGrow: 1,
    minWidth: 180,
    borderWidth: 1,
    borderColor: "#D6D6D6",
    borderRadius: 8,
    padding: 12,
    fontFamily: "DashboardRegular",
    fontSize: 16,
    backgroundColor: "white",
  },
  filter: {
    width: "27%",
    minWidth: 180,
    height: 38,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#D6D6D6",
    borderRadius: 7,
  },
  filterLabel: {
    fontFamily: "DashboardMedium",
    fontSize: 13,
    color: "#6C757D",
  },
  // Header and Rows share proportional columns so they stay aligned
  tableScroll: { flexGrow: 1 },
  table: { minWidth: 760, flexGrow: 1 },
  tableHeader: {
    flexDirection: "row",
    alignItems: "center",
    height: 36,
    paddingHorizontal: 14,
    backgroundColor: "#F9F6F1",
    borderWidth: 1,
    borderColor: "#DDD",
    borderTopLeftRadius: 7,
    borderTopRightRadius: 7,
  },
  headerText: { fontFamily: "DashboardMedium", fontSize: 13, color: "#3C4147" },
  row: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    minHeight: 49,
    borderWidth: 1,
    borderTopWidth: 0,
    borderColor: "#DDD",
  },
  nameColumn: {
    width: "27%",
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  column: { width: "18%", alignItems: "center", textAlign: "center" },
  actionColumn: { width: "19%", alignItems: "center", textAlign: "center" },
  thumbnail: { width: 56, height: 35, borderRadius: 4 },
  rowCopy: { flex: 1, paddingRight: 8 },
  rowName: { fontFamily: "DashboardMedium", fontSize: 15, color: "#3C4147" },
  buildingName: {
    fontFamily: "DashboardMedium",
    fontSize: 11,
    color: "#3C4147",
  },
  rowDescription: {
    fontFamily: "DashboardRegular",
    fontSize: 8,
    color: "#6C757D",
    marginTop: 2,
  },
  badge: {
    fontFamily: "DashboardMedium",
    color: "white",
    fontSize: 10,
    textAlign: "center",
    borderRadius: 20,
    minWidth: 75,
    paddingHorizontal: 8,
    paddingVertical: 2,
    overflow: "hidden",
  },
  maintenanceText: { color: "#971F2A" },
  floorCount: { fontFamily: "DashboardMedium", fontSize: 18, color: "#6C757D" },
  editButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  resultCount: {
    fontFamily: "DashboardRegular",
    fontSize: 11,
    color: "#6C757D",
    marginTop: 12,
  },
  empty: { padding: 24, textAlign: "center" },
  // Filters and Local Editor
  overlay: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  backdrop: { ...StyleSheet.absoluteFill, backgroundColor: "rgba(0,0,0,0.4)" },
  dialog: {
    backgroundColor: "white",
    borderRadius: 20,
    padding: 24,
    width: "100%",
    maxWidth: 550,
    maxHeight: "90%",
  },
  option: { padding: 14 },
  fieldLabel: {
    fontFamily: "DashboardMedium",
    fontSize: 16,
    marginTop: 14,
    marginBottom: 6,
    textTransform: "capitalize",
  },
  choices: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  choice: { borderWidth: 1, borderColor: "#DDD", borderRadius: 8, padding: 10 },
  dialogActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
    marginTop: 20,
  },
  primary: {
    backgroundColor: "#AF2532",
    borderRadius: 8,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  white: { fontFamily: "DashboardMedium", color: "white", fontSize: 15 },
});
