import { StyleSheet } from "react-native";

// AdminLoginScreen: responsive desktop split layout and stacked phone layout.
export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: "#991F2B" },
  page: { flexGrow: 1, flexDirection: "row", minHeight: 680 },
  pageCompact: { flexDirection: "column", minHeight: 0 },
  // Branding Background and Decorative Assets
  brandPanel: {
    flex: 0.47,
    backgroundColor: "#991F2B",
    overflow: "hidden",
    minHeight: 680,
  },
  brandCompact: { flex: 0, minHeight: 320 },
  campus: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: "65%",
    opacity: 0.2,
  },
  watermark: {
    position: "absolute",
    top: -80,
    right: -40,
    width: 290,
    height: 290,
    opacity: 0.1,
  },
  waves: { position: "absolute", left: 0, right: 0, bottom: 0, height: "32%" },
  topDivider: {
    flexDirection: "row",
    alignItems: "center",
    gap: 18,
    paddingHorizontal: 24,
    paddingTop: 18,
  },
  line: { flex: 1, height: 1, backgroundColor: "#CA8A70" },
  dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: "#FEBF1F" },
  plane: { width: 30, height: 30 },
  // Logo, Name and Tagline
  brandContent: { padding: 26, zIndex: 1 },
  brandRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
  },
  logo: { width: "45%", aspectRatio: 1 },
  logoCompact: { width: 130, height: 130 },
  brandWords: { flexShrink: 1 },
  brandText: {
    fontSize: 46,
    color: "white",
    textAlign: "center",
    fontWeight: "900",
    textShadowColor: "#64131C",
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 3,
  },
  brandTextCompact: { fontSize: 34 },
  brandFont: { fontFamily: "AdminBrand", fontWeight: "normal" },
  gold: { color: "#FEBF1F" },
  taglineDivider: {
    height: 1,
    backgroundColor: "#C78835",
    width: "70%",
    marginTop: 12,
    marginBottom: 10,
  },
  taglineRow: { flexDirection: "row", gap: 18 },
  taglineItem: { flexDirection: "row", alignItems: "center", gap: 18 },
  tagline: { fontSize: 20, color: "white" },
  // Login Panel and Typography
  formPanel: {
    flex: 0.53,
    backgroundColor: "#FFFCFA",
    paddingHorizontal: 48,
    paddingVertical: 70,
    justifyContent: "center",
    overflow: "hidden",
  },
  formCompact: { flex: 0, paddingHorizontal: 24, paddingVertical: 36 },
  formBackground: { ...StyleSheet.absoluteFill, opacity: 0.5 },
  form: { width: "100%", maxWidth: 710, alignSelf: "center" },
  avatar: { width: 110, height: 104, alignSelf: "center" },
  heading: { fontSize: 30, color: "#741324", textAlign: "center" },
  subtitle: {
    fontSize: 20,
    color: "#3C4147",
    textAlign: "center",
    marginBottom: 24,
  },
  regular: { fontFamily: "AdminRegular" },
  medium: { fontFamily: "AdminMedium" },
  bold: { fontFamily: "AdminBold" },
  // Input Fields and Buttons
  label: { fontSize: 20, color: "#3C4147", marginBottom: 6, marginTop: 14 },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    minHeight: 60,
    paddingLeft: 16,
    paddingRight: 8,
    borderWidth: 1,
    borderColor: "#ADB1B4",
    borderRadius: 14,
    backgroundColor: "white",
  },
  input: { flex: 1, minWidth: 0, height: 58, fontSize: 18, color: "#3C4147" },
  eyeButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  loginButton: {
    marginTop: 28,
    minHeight: 60,
    borderRadius: 24,
    backgroundColor: "#AF2532",
    alignItems: "center",
    justifyContent: "center",
  },
  loginText: { fontSize: 24, color: "white" },
  pressed: { opacity: 0.8 },
  message: { color: "#9E212D", fontSize: 16, marginTop: 12 },
});
