import { StyleSheet } from "react-native";
// Shared placement for building, floor-list and room editor popups.
export const styles = StyleSheet.create({
  // Modal Shell and Header
  overlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  backdrop: { ...StyleSheet.absoluteFill, backgroundColor: "rgba(0,0,0,0.45)" },
  dialog: {
    width: "100%",
    maxHeight: "94%",
    backgroundColor: "white",
    borderRadius: 28,
    overflow: "hidden",
  },
  buildingDialog: { maxWidth: 990 },
  floorsDialog: { maxWidth: 815 },
  roomDialog: { maxWidth: 579 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    paddingHorizontal: 24,
    paddingVertical: 16,
  },
  title: {
    flex: 1,
    fontFamily: "DashboardMedium",
    fontSize: 28,
    color: "#A42330",
  },
  close: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  content: { paddingHorizontal: 40, paddingBottom: 30 },
  hidden: { display: "none" },
  backArrow: { fontSize: 44, color: "#FEBF1F" },
  // Building Photo and Form Columns
  columns: { flexDirection: "row", gap: 40 },
  stacked: { flexDirection: "column" },
  photoColumn: { flex: 1 },
  formColumn: { flex: 1 },
  photo: { width: "100%", aspectRatio: 1.64, borderRadius: 20, marginTop: 10 },
  removePhoto: {
    position: "absolute",
    top: 20,
    right: 14,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#3C4147",
    alignItems: "center",
    justifyContent: "center",
  },
  removeText: { color: "white", fontSize: 28 },
  photoPlaceholder: {
    height: 180,
    backgroundColor: "#F9F6F1",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    borderRadius: 16,
  },
  link: { color: "#A42330" },
  // Required Fields, Dropdowns and Character Counter
  field: { marginBottom: 20 },
  label: {
    fontFamily: "DashboardMedium",
    fontSize: 18,
    color: "#34465C",
    marginBottom: 4,
  },
  required: { color: "#F41227" },
  input: {
    borderWidth: 1,
    borderColor: "#D2D2D2",
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontFamily: "DashboardRegular",
    fontSize: 18,
    color: "#34465C",
    backgroundColor: "white",
  },
  description: { height: 118, textAlignVertical: "top" },
  counter: {
    textAlign: "right",
    fontFamily: "DashboardRegular",
    fontSize: 16,
    color: "#6C757D",
    marginTop: 3,
  },
  select: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#D2D2D2",
    borderRadius: 10,
    padding: 12,
    gap: 10,
  },
  inputText: {
    flex: 1,
    fontFamily: "DashboardRegular",
    fontSize: 18,
    color: "#34465C",
  },
  // Shared proceed-arrow: right-facing asset rotated for dropdown state.
  arrowDown: { transform: [{ rotate: "90deg" }] },
  arrowUp: { transform: [{ rotate: "-90deg" }] },
  options: {
    borderWidth: 1,
    borderColor: "#DDD",
    borderRadius: 8,
    backgroundColor: "white",
  },
  option: { padding: 10 },
  error: { color: "#A42330", marginBottom: 12 },
  // Navigation and Save/Cancel
  manage: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    borderWidth: 1,
    borderColor: "#A42330",
    borderRadius: 10,
    padding: 14,
    marginTop: 8,
  },
  manageText: {
    flex: 1,
    fontFamily: "DashboardMedium",
    fontSize: 23,
    color: "#971F2A",
  },
  actions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 14,
    marginTop: 26,
  },
  cancel: {
    flex: 1,
    maxWidth: 244,
    minHeight: 54,
    borderWidth: 1.5,
    borderColor: "#A42330",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  save: {
    flex: 1,
    maxWidth: 244,
    minHeight: 54,
    backgroundColor: "#A0222E",
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  cancelText: { fontFamily: "DashboardMedium", fontSize: 24, color: "#A0222E" },
  saveText: { fontFamily: "DashboardMedium", fontSize: 24, color: "white" },
  // Floors Accordion and Data-driven Room Rows
  buildingSubtitle: {
    fontFamily: "DashboardRegular",
    fontSize: 23,
    color: "#486BAC",
    marginBottom: 22,
  },
  floorBlock: {
    borderWidth: 1,
    borderColor: "#D2D2D2",
    borderRadius: 10,
    overflow: "hidden",
    marginBottom: 10,
  },
  floorHeading: {
    flexDirection: "row",
    alignItems: "center",
    gap: 20,
    padding: 12,
    backgroundColor: "#F9F1F3",
  },
  floorTitle: {
    flex: 1,
    fontFamily: "DashboardMedium",
    fontSize: 25,
    color: "#A42330",
  },
  roomRow: {
    flexDirection: "row",
    alignItems: "center",
    minHeight: 72,
    borderTopWidth: 1,
    borderColor: "#DDD",
    paddingVertical: 8,
  },
  cell: {
    flex: 1,
    textAlign: "center",
    alignItems: "center",
    fontFamily: "DashboardRegular",
    fontSize: 20,
    color: "#486BAC",
  },
  tableHeading: { fontFamily: "DashboardMedium", fontSize: 20 },
  editButton: {
    minWidth: 44,
    minHeight: 44,
    justifyContent: "center",
    alignItems: "center",
  },
  empty: { padding: 20, color: "#6C757D" },
});
